#%RAML 1.0 Trait
headers:
  "clientKey":
    type: string
    required: false
    example: "dfsdfhj43njfsdf-dfe9"
  "firstName":
    type: string
    required: false
    example: "Uma"
  "middleName":
    type: string
    required: false
    example: "Rao"
  "lastName":
    type: string
    required: false
    example: "Madasu"
  "birthDate":
    type: date-only
    required: false
    example: 1992-12-24
  "Height":
    type: string
    required: false
    example: "10.5"
  "Weight":
    type: string
    required: false
    example: "160lbs"
  "billingStreet":
    type: string
    required: false
    example: "2337"
  "billingCity":
    type: string
    required: false
    example: "promenade blvd"
  "billingState":
    type: string
    required: false
    example: "Montgomery"
  "billingPostalCode":
    type: integer
    required: false
    example: 36106
  "billingCountry":
    type: string
    required: false
    example: USA
  "createdDate":
    type: date-only
    required: false
    example: 2020-10-18